services:
  couchbase:
    build: .
    ports:
      - "8080:8080"  
      - "8081:8081"  
      - "8082:8082"  
      - "8083:8083"  
      - "8084:8084" 
    volumes:
      - couchbase_data:/opt/couchbase/var
volumes:
  couchbase_data: